version: 2
jobs:
  test:
    docker:
      - image: circleci/android:api-28
    steps:
      - run:
          name: Build debug APK and release APK
          command: |
            ./gradlew clean
            ./gradlew check