version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Build debug APK and release APK
          command: |
            ./gradlew clean
            ./gradlew check
      - store_test_results:
          path: app/build/test-results